In [1]:
import tensorflow as tf

# initialization of tensors

In [4]:
x = tf.constant(4,shape=(1,1),dtype=tf.float32)
x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [5]:
x = tf.constant([[1,2,3],[4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [6]:
x = tf.ones((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [7]:
x = tf.zeros((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [8]:
x = tf.eye(3) # eye for identity matrix
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [2]:
x = tf.random.normal((3,3),mean=0,stddev=1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.2499983 ,  0.56428117,  0.81072736],
       [ 1.2590429 ,  1.0195758 , -0.16826019],
       [ 0.37989894,  1.0304794 , -1.0262505 ]], dtype=float32)>

In [3]:
x = tf.random.uniform((1,3),minval=0,maxval=1)
x

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.48407018, 0.6122004 , 0.3491423 ]], dtype=float32)>

In [4]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [5]:
x = tf.range(start=1,limit=10,delta=2)
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [6]:
x = tf.cast(x,dtype=tf.float64)
x

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

# mathematical operations

In [7]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

In [8]:
z = tf.add(x,y)  # z = x+y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10])>

In [9]:
z = tf.subtract(x,y) # z = x-y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4])>

In [10]:
z = tf.divide(x,y) # z = x/y
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [11]:
z = tf.multiply(x,y) # z = x*y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21])>

In [12]:
z = tf.tensordot(x,y,axes=1)
# z = tf.reduce_sum(x*y,axis=0)
z

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [13]:
z = x ** 5
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1,  32, 243])>

In [14]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

In [15]:
z = tf.matmul(x,y) # z = x@y
z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 3.4034793 , -0.7577497 , -1.9077668 , -2.2081566 ],
       [-1.3537241 ,  0.49896267,  1.203018  , -1.6207417 ]],
      dtype=float32)>

# indexing

In [21]:
x = tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [22]:
indices = tf.constant([0,3])
x_ind = tf.gather(x,indices)
x_ind

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2])>

In [27]:
x = tf.constant([[1,2],[3,4],[5,6]])
print(x[0,:])
print(x[0:2,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


# reshaping

In [28]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [29]:
x = tf.reshape(x,(3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [30]:
x = tf.transpose(x,perm=[1,0])
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])>

# neural networks with sequential and functional API

In [32]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

In [34]:
(X_train,Y_train),(X_test,Y_test) = mnist.load_data()

In [35]:
print(X_train.shape)

(60000, 28, 28)


In [38]:
X_train = X_train.reshape(-1,28*28).astype("float32") / 255.0
X_test = X_test.reshape(-1,28*28).astype("float32") / 255.0

#### sequential API (very convenient , not very flexible)

In [47]:
model = keras.Sequential(
    [
        keras.Input(shape=(28,28)),
        layers.Dense(512,activation='relu'),
        layers.Dense(256,activation='relu'),
        layers.Dense(10),
    ]
)
print(model.summary())

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 28, 512)             │          14,848 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 28, 256)             │         131,328 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 28, 10)              │           2,570 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 148,746 (581.04 KB)

 Trainable params: 148,746 (581.04 KB)

 Non-trainable params: 0 (0.00 B)

None


In [56]:
model = keras.Model(inputs=model.inputs, outputs=[layer.output for layer in model.layers])

In [42]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy'],
)

In [43]:
model.fit(X_train,Y_train,epochs=5,batch_size=32,verbose=2)

Epoch 1/5
1875/1875 - 22s - 12ms/step - accuracy: 0.1579 - loss: 2.3296
Epoch 2/5
1875/1875 - 18s - 10ms/step - accuracy: 0.1583 - loss: 2.3026
Epoch 3/5
1875/1875 - 18s - 10ms/step - accuracy: 0.1583 - loss: 2.3026
Epoch 4/5
1875/1875 - 18s - 10ms/step - accuracy: 0.1583 - loss: 2.3026
Epoch 5/5
1875/1875 - 18s - 10ms/step - accuracy: 0.1583 - loss: 2.3026


In [44]:
model.evaluate(X_test,Y_test,batch_size=32,verbose=2)

313/313 - 1s - 4ms/step - accuracy: 0.2295 - loss: 2.5430


[2.5430216789245605, 0.22949999570846558]

In [57]:
features = model.predict(X_train)

1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step


In [58]:
for feature in features:
    print(feature.shape)

(60000, 784)
(60000, 512)
(60000, 256)
(60000, 10)


# functional API

In [60]:
inputs = keras.Input(shape=(784,))
x = layers.Dense(512,activation='relu')(inputs)
x = layers.Dense(256,activation='relu')(x)
outputs = layers.Dense(10,activation='softmax')(x)
model = keras.Model(inputs=inputs,outputs=outputs)

In [61]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy'],
)

In [62]:
model.fit(X_train,Y_train,epochs=5,batch_size=32,verbose=2)

Epoch 1/5
1875/1875 - 35s - 19ms/step - accuracy: 0.8255 - loss: 0.5775
Epoch 2/5
1875/1875 - 18s - 10ms/step - accuracy: 0.9137 - loss: 0.2922
Epoch 3/5
1875/1875 - 18s - 10ms/step - accuracy: 0.9347 - loss: 0.2196
Epoch 4/5
1875/1875 - 18s - 10ms/step - accuracy: 0.9494 - loss: 0.1687
Epoch 5/5
1875/1875 - 18s - 10ms/step - accuracy: 0.9584 - loss: 0.1371


In [63]:
model.evaluate(X_test,Y_test,batch_size=32,verbose=2)

313/313 - 1s - 4ms/step - accuracy: 0.9458 - loss: 16.1761


[16.17609214782715, 0.9458000063896179]