In [1]:
from keras import Sequential
from keras.layers import Dense,SimpleRNN

In [2]:
model = Sequential()

model.add(SimpleRNN(3,input_shape=(4,5)))
model.add(Dense(1,activation='sigmoid'))

model.summary()

C:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)               │ (None, 3)                   │              27 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [3]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

(5, 3)


array([[ 0.5244531 ,  0.4965152 ,  0.61374575],
       [ 0.74397355, -0.6125585 ,  0.44055814],
       [-0.19036335, -0.15491891,  0.39351577],
       [ 0.23873812, -0.86589885, -0.76470304],
       [ 0.5004129 ,  0.6527471 , -0.52551746]], dtype=float32)

In [4]:
print(model.get_weights()[3].shape)
model.get_weights()[3]

(3, 1)


array([[-0.8569022 ],
       [-0.3263849 ],
       [ 0.22956169]], dtype=float32)

In [5]:
print(model.get_weights()[4].shape)
model.get_weights()[4]

(1,)


array([0.], dtype=float32)

# INTEGER ENCODING SIMPLE RNN

In [6]:
import numpy as np

In [7]:
docs = ['go india',
        'india india',
        'hip hip hurray',
        'jeetega bhai jeetega india jeetega',
        'bharat mata ki jai',
        'kohli kohli',
        'sachin sachin',
        'dhoni dhoni',
        'modi ji ki jay',
        'inquilab zindabad']

In [8]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='dhruv')

In [9]:
tokenizer.fit_on_texts(docs)

In [10]:
tokenizer.word_index

{'dhruv': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'kohli': 6,
 'sachin': 7,
 'dhoni': 8,
 'go': 9,
 'hurray': 10,
 'bhai': 11,
 'bharat': 12,
 'mata': 13,
 'jai': 14,
 'modi': 15,
 'ji': 16,
 'jay': 17,
 'inquilab': 18,
 'zindabad': 19}

In [11]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 1),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('jay', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

In [12]:
tokenizer.document_count

10

In [13]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 2],
 [2, 2],
 [4, 4, 10],
 [3, 11, 3, 2, 3],
 [12, 13, 5, 14],
 [6, 6],
 [7, 7],
 [8, 8],
 [15, 16, 5, 17],
 [18, 19]]

In [14]:
from keras.utils import pad_sequences

In [15]:
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 10,  0,  0],
       [ 3, 11,  3,  2,  3],
       [12, 13,  5, 14,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [15, 16,  5, 17,  0],
       [18, 19,  0,  0,  0]])

### sentiment analysis

In [16]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [17]:
(X_train,Y_train),(X_test,Y_test) = imdb.load_data()

In [18]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [19]:
X_train.shape

(25000,)

In [20]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [21]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [22]:
X_train.shape

(25000, 50)

In [23]:
model = Sequential()

model.add(SimpleRNN(32,input_shape=(50,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)             │ (None, 32)                  │           1,088 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X_train,Y_train,epochs=5,validation_data=(X_test,Y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 16s 17ms/step - accuracy: 0.5024 - loss: 0.6946 - val_accuracy: 0.5083 - val_loss: 0.6934
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - accuracy: 0.4979 - loss: 0.6929 - val_accuracy: 0.5060 - val_loss: 0.6937
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - accuracy: 0.5082 - loss: 0.6928 - val_accuracy: 0.5028 - val_loss: 0.6960
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 16ms/step - accuracy: 0.5147 - loss: 0.6926 - val_accuracy: 0.5026 - val_loss: 0.6943
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - accuracy: 0.5116 - loss: 0.6931 - val_accuracy: 0.5021 - val_loss: 0.6937


# EMBEDDING LAYER

In [25]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense, Input

In [26]:
docs = ['go india',
        'india india',
        'hip hip hurray',
        'jeetega bhai jeetega india jeetega',
        'bharat mata ki jai',
        'kohli kohli',
        'sachin sachin',
        'dhoni dhoni',
        'modi ji ki jay',
        'inquilab zindabad']

In [27]:
tokenizer = Tokenizer()

In [28]:
tokenizer.fit_on_texts(docs)

In [29]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[8, 1],
 [1, 1],
 [3, 3, 9],
 [2, 10, 2, 1, 2],
 [11, 12, 4, 13],
 [5, 5],
 [6, 6],
 [7, 7],
 [14, 15, 4, 16],
 [17, 18]]

In [30]:
max_length = 5
padded_sequences = pad_sequences(sequences, padding='post', maxlen=max_length)
padded_sequences

array([[ 8,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3,  9,  0,  0],
       [ 2, 10,  2,  1,  2],
       [11, 12,  4, 13,  0],
       [ 5,  5,  0,  0,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [14, 15,  4, 16,  0],
       [17, 18,  0,  0,  0]])

In [31]:
print("Word Index Length:", len(tokenizer.word_index))
print("Sequences:", sequences)
print("Padded Sequences:", padded_sequences)

Word Index Length: 18
Sequences: [[8, 1], [1, 1], [3, 3, 9], [2, 10, 2, 1, 2], [11, 12, 4, 13], [5, 5], [6, 6], [7, 7], [14, 15, 4, 16], [17, 18]]
Padded Sequences: [[ 8  1  0  0  0]
 [ 1  1  0  0  0]
 [ 3  3  9  0  0]
 [ 2 10  2  1  2]
 [11 12  4 13  0]
 [ 5  5  0  0  0]
 [ 6  6  0  0  0]
 [ 7  7  0  0  0]
 [14 15  4 16  0]
 [17 18  0  0  0]]


In [32]:
model = Sequential()
model.add(Input(shape=(max_length,)))
model.add(Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=2, input_length=max_length))
model.summary()

C:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 5, 2)                │              38 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 38 (152.00 B)

 Trainable params: 38 (152.00 B)

 Non-trainable params: 0 (0.00 B)

In [33]:
pred = model.predict(padded_sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step
[[[ 1.1378132e-02  2.2513632e-02]
  [ 2.4019230e-02  1.8145923e-02]
  [ 8.6315162e-03  2.8768543e-02]
  [ 8.6315162e-03  2.8768543e-02]
  [ 8.6315162e-03  2.8768543e-02]]

 [[ 2.4019230e-02  1.8145923e-02]
  [ 2.4019230e-02  1.8145923e-02]
  [ 8.6315162e-03  2.8768543e-02]
  [ 8.6315162e-03  2.8768543e-02]
  [ 8.6315162e-03  2.8768543e-02]]

 [[ 3.8767647e-02  4.7790121e-02]
  [ 3.8767647e-02  4.7790121e-02]
  [ 4.1638803e-02  3.5810698e-02]
  [ 8.6315162e-03  2.8768543e-02]
  [ 8.6315162e-03  2.8768543e-02]]

 [[ 5.8688223e-05 -1.9801056e-02]
  [ 3.5903383e-02 -4.1926753e-02]
  [ 5.8688223e-05 -1.9801056e-02]
  [ 2.4019230e-02  1.8145923e-02]
  [ 5.8688223e-05 -1.9801056e-02]]

 [[ 3.8703885e-02 -3.7354030e-02]
  [-4.8563432e-02  1.4244940e-02]
  [ 2.8649237e-02 -4.9425114e-02]
  [ 2.3758087e-02  2.6565742e-02]
  [ 8.6315162e-03  2.8768543e-02]]

 [[-1.7744362e-02  4.6046171e-02]
  [-1.7744362e-02  4.6046171e-02]
  [ 8.6315162e-03  2.8768543e-02]

### sentiment analysis

In [34]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense, Input

In [35]:
(X_train, Y_train), (X_test, Y_test) = imdb.load_data(num_words=10000)

In [36]:
max_length = 50
X_train = pad_sequences(X_train, padding='post', maxlen=max_length)
X_test = pad_sequences(X_test, padding='post', maxlen=max_length)

In [37]:
X_train.shape

(25000, 50)

In [38]:
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=2, input_length=max_length))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_2 (SimpleRNN)             │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [39]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X_train,Y_train,epochs=5,validation_data=(X_test,Y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 21ms/step - accuracy: 0.5643 - loss: 0.6600 - val_accuracy: 0.7980 - val_loss: 0.4419
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 16s 20ms/step - accuracy: 0.8276 - loss: 0.3960 - val_accuracy: 0.7970 - val_loss: 0.4371
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 16s 20ms/step - accuracy: 0.8722 - loss: 0.3198 - val_accuracy: 0.7884 - val_loss: 0.4584
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 16s 21ms/step - accuracy: 0.8922 - loss: 0.2757 - val_accuracy: 0.7944 - val_loss: 0.5021
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 16s 20ms/step - accuracy: 0.9042 - loss: 0.2547 - val_accuracy: 0.7946 - val_loss: 0.5086
