# REGRESSION

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
def initialize_parameters(layer_dims):
  
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)         

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
      
  return parameters

In [5]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [6]:
def linear_forward(A_prev, W, b):
  
  Z = np.dot(W.T, A_prev) + b
  
  return Z

In [7]:
# Forward Propagation

def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2          
  
  for l in range(1, L+1):
    A_prev = A 
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    print("A"+str(l-1)+": ", A_prev)
    print("W"+str(l)+": ", Wl)
    print("b"+str(l)+": ", bl)
    print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    print("A"+str(l)+": ", A)
    print("**"*20)
          
  return A,A_prev

In [8]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [9]:
y_hat = y_hat[0][0]

In [10]:
A1

array([[1.6],
       [1.6]])

In [11]:
loss = (y-y_hat)**2
loss

13.542399999999997

In [12]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [13]:
update_parameters(parameters,y,y_hat,A1,X)

In [14]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [15]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
****************************************
A1:  [[1.70612461]
 [1.70612461]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
----------------------------------------
A2:  [[0.50054357]]
****************************************


In [16]:
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.11458955, 0.1168776 ],
        [0.11458955, 0.1168776 ]]),
 'b1': array([[0.0019667],
        [0.0019667]]),
 'W2': array([[0.12712927],
        [0.12712927]]),
 'b2': array([[0.13612818]])}

In [17]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[2][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

A0:  [[ 6]
 [10]]
W1:  [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1:  [[0.0019667]
 [0.0019667]]
----------------------------------------
A1:  [[1.83539945]
 [1.87200826]]
****************************************
A1:  [[1.83539945]
 [1.87200826]]
W2:  [[0.12712927]
 [0.12712927]]
b2:  [[0.13612818]]
----------------------------------------
A2:  [[0.6074482]]
****************************************


In [18]:
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.12409711, 0.13272353],
        [0.12412266, 0.13276611]]),
 'b1': array([[0.00355129],
        [0.00355555]]),
 'W2': array([[0.14692424],
        [0.14731907]]),
 'b2': array([[0.15810417]])}

In [19]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

A0:  [[ 5]
 [12]]
W1:  [[0.12409711 0.13272353]
 [0.12412266 0.13276611]]
b1:  [[0.00355129]
 [0.00355555]]
----------------------------------------
A1:  [[2.11350869]
 [2.26036654]]
****************************************
A1:  [[2.11350869]
 [2.26036654]]
W2:  [[0.14692424]
 [0.14731907]]
b2:  [[0.15810417]]
----------------------------------------
A2:  [[0.80162493]]
****************************************


In [20]:
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.13482804, 0.15847776],
        [0.1349909 , 0.15884991]]),
 'b1': array([[0.00569748],
        [0.0057292 ]]),
 'W2': array([[0.17312488],
        [0.17534027]]),
 'b2': array([[0.18773702]])}

In [21]:
parameters = initialize_parameters([2,2,1])
epochs=5

for i in range(epochs):

    Loss = []

    for j in range(df.shape[0]):
        X = df[['cgpa','profile_score']].values[j].reshape(2,1)
        y = df[['lpa']].values[j][0]

        y_hat,A1 = L_layer_forward(X,parameters)
        y_hat = y_hat[0][0]

        update_parameters(parameters,y,y_hat,A1,X)
        Loss.append((y - y_hat)**2)

    print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
****************************************
A1:  [[1.70612461]
 [1.70612461]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
----------------------------------------
A2:  [[0.50054357]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1:  [[0.0019667]
 [0.0019667]]
----------------------------------------
A1:  [[1.83539945]
 [1.87200826]]
****************************************
A1:  [[1.83539945]
 [1.87200826]]
W2:  [[0.12712927]
 [0.127

{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

# using keras

In [2]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [3]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [4]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [5]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

C:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
model.get_weights()

[array([[ 1.08542   ,  1.0164856 ],
        [-0.94612277, -0.771124  ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.99069875],
        [ 0.4413395 ]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
              np.array([0.,0.],dtype=np.float32),
              np.array([[0.1],[0.1]],dtype=np.float32),
              np.array([0.],dtype=np.float32)]

In [9]:
model.set_weights(new_weights)

In [10]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
model.compile(loss='mean_squared_error',optimizer=Adam(learning_rate=0.001))

In [12]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - loss: 31.8140
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 33.3377  
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 28.9131  
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.5169  
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 29.8628  
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20.4269  
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31.9477 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 20.7641 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 28.1381 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 28.3601 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 24.5483  
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 23.4357  
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 28.6850  
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 26.5020 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.6733  
Epoch 16/7

In [13]:
model.get_weights()

[array([[0.3736383 , 0.3736383 ],
        [0.36543885, 0.36543885]], dtype=float32),
 array([0.2722255, 0.2722255], dtype=float32),
 array([[0.37282798],
        [0.37282798]], dtype=float32),
 array([0.20455806], dtype=float32)]

# CLASSIFICATION

In [15]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,12,0]],columns=['cgpa','profile_score','placed'])
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5             12       0

In [16]:
def initialize_parameters(layer_dims):
  
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)         

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
      
  return parameters

In [17]:
def sigmoid(Z):
    A = 1/(1+np.exp(-Z))
    return A

In [18]:
def linear_forward(A_prev, W, b):

    Z = np.dot(W.T, A_prev) + b
    A = sigmoid(Z)
    return A

In [19]:
# Forward Propagation

def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2          
  
  for l in range(1, L+1):
    A_prev = A 
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    print("A"+str(l-1)+": ", A_prev)
    print("W"+str(l)+": ", Wl)
    print("b"+str(l)+": ", bl)
    print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    print("A"+str(l)+": ", A)
    print("**"*20)
          
  return A,A_prev

In [20]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [22]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['placed']].values[0][0]

parameters = initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.83201839]
 [0.83201839]]
****************************************
A1:  [[0.83201839]
 [0.83201839]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.54150519]]
****************************************


In [23]:
update_parameters(parameters,y,y_hat,A1,X)
print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))
parameters

Loss for this student -  0.613402628898913


{'W1': array([[0.10000513, 0.10000513],
        [0.10000513, 0.10000513]]),
 'b1': array([[6.41054186e-07],
        [6.41054186e-07]]),
 'W2': array([[0.10003815],
        [0.10003815]]),
 'b2': array([[0.100084]])}

In [24]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['placed']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

A0:  [[7]
 [9]]
W1:  [[0.10000513 0.10000513]
 [0.10000513 0.10000513]]
b1:  [[6.41054186e-07]
 [6.41054186e-07]]
----------------------------------------
A1:  [[0.83202994]
 [0.83202994]]
****************************************
A1:  [[0.83202994]
 [0.83202994]]
W2:  [[0.10003815]
 [0.10003815]]
b2:  [[0.100084]]
----------------------------------------
A2:  [[0.56624659]]
****************************************


In [25]:
update_parameters(parameters,y,y_hat,A1,X)
print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))
parameters

Loss for this student -  0.568725622654268


{'W1': array([[0.10000937, 0.10001059],
        [0.10000937, 0.10001059]]),
 'b1': array([[1.24770113e-06],
        [1.24770113e-06]]),
 'W2': array([[0.10007424],
        [0.10007424]]),
 'b2': array([[0.10011761]])}

In [26]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['placed']].values[2][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

A0:  [[ 6]
 [10]]
W1:  [[0.10000937 0.10001059]
 [0.10000937 0.10001059]]
b1:  [[1.24770113e-06]
 [1.24770113e-06]]
----------------------------------------
A1:  [[0.83203952]
 [0.83204224]]
****************************************
A1:  [[0.83203952]
 [0.83204224]]
W2:  [[0.10007424]
 [0.10007424]]
b2:  [[0.10011761]]
----------------------------------------
A2:  [[0.56627013]]
****************************************


In [27]:
update_parameters(parameters,y,y_hat,A1,X)
print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))
parameters

Loss for this student -  0.8353333695154365


{'W1': array([[0.10000463, 0.10000267],
        [0.10000463, 0.10000267]]),
 'b1': array([[4.56125378e-07],
        [4.56135584e-07]]),
 'W2': array([[0.10002712],
        [0.10002712]]),
 'b2': array([[0.09997049]])}

In [28]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['placed']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

A0:  [[ 5]
 [12]]
W1:  [[0.10000463 0.10000267]
 [0.10000463 0.10000267]]
b1:  [[4.56125378e-07]
 [4.56135584e-07]]
----------------------------------------
A1:  [[0.84554506]
 [0.84554073]]
****************************************
A1:  [[0.84554506]
 [0.84554073]]
W2:  [[0.10002712]
 [0.10002712]]
b2:  [[0.09997049]]
----------------------------------------
A2:  [[0.56687807]]
****************************************


In [29]:
update_parameters(parameters,y,y_hat,A1,X)
print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))
parameters

Loss for this student -  0.8367359874723076


{'W1': array([[0.10000092, 0.09999379],
        [0.10000092, 0.09999379]]),
 'b1': array([[-2.84055419e-07],
        [-2.84062197e-07]]),
 'W2': array([[0.09997919],
        [0.09997919]]),
 'b2': array([[0.0999225]])}

In [30]:
parameters = initialize_parameters([2,2,1])
epochs=5

for i in range(epochs):

    Loss = []

    for j in range(df.shape[0]):
        X = df[['cgpa','profile_score']].values[j].reshape(2,1)
        y = df[['placed']].values[j][0]

        y_hat,A1 = L_layer_forward(X,parameters)
        y_hat = y_hat[0][0]

        update_parameters(parameters,y,y_hat,A1,X)
        Loss.append(-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

    print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.83201839]
 [0.83201839]]
****************************************
A1:  [[0.83201839]
 [0.83201839]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.54150519]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.10000513 0.10000513]
 [0.10000513 0.10000513]]
b1:  [[6.41054186e-07]
 [6.41054186e-07]]
----------------------------------------
A1:  [[0.83202994]
 [0.83202994]]
****************************************
A1:  [[0.83202994]
 [0.83202994]]
W2:  [[0.10003815]
 [0.10003815]]
b2:  [[0.100084]]
----------------------------------------
A2:  [[0.56624659]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[0.10000937 0.10001059]
 [0.10000937 0.10001059]]
b1:  [[1.24770113e-06]
 [1.24770113e-06]]
----------------------------------------
A1:  [[0.83203952]
 [0.83204224]]
****************************************
A1: 

{'W1': array([[0.10000352, 0.09996787],
        [0.10000352, 0.09996786]]),
 'b1': array([[-1.55677833e-06],
        [-1.55711273e-06]]),
 'W2': array([[0.09988778],
        [0.09988778]]),
 'b2': array([[0.0998311]])}

# using keras

In [31]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [32]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,12,0]],columns=['cgpa','profile_score','placed'])
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5             12       0

In [33]:
model = Sequential()
model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

C:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [34]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
model.get_weights()

[array([[-0.72472924, -0.9425905 ],
        [-0.3621887 , -1.2177973 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.05546153],
        [-0.3048681 ]], dtype=float32),
 array([0.], dtype=float32)]

In [36]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
              np.array([0.,0.],dtype=np.float32),
              np.array([[0.1],[0.1]],dtype=np.float32),
              np.array([0.],dtype=np.float32)]

In [37]:
model.set_weights(new_weights)

In [38]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [40]:
model.compile(loss='binary_crossentropy',optimizer=Adam(learning_rate=0.001))

In [43]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.7084
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7356 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7073 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6859 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7178 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7179 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6599 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7174 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6600 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6600  
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7328 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6759 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7168 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7314 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7311 
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━━

In [44]:
model.get_weights()

[array([[0.12162478, 0.12162478],
        [0.03866272, 0.03866272]], dtype=float32),
 array([-0.02463497, -0.02463497], dtype=float32),
 array([[0.08072586],
        [0.08072586]], dtype=float32),
 array([-0.02088566], dtype=float32)]